### ISSUE TITLE
Conclusions

### ISSUE THREAD

**Issue by tom--** [samdark/realpath_cache_tuner#1]
I would suggest being more generous in the recommendations because,

- it can be difficult to be sure you've fully warmed the cache, or to know how far you have warmed it
- realpath cache is important, you don't want to run out
- realpath cache requires, in the overall view of the server, very little memory so it's not the right place to try and save a few kilo bytes.

Hence my recommendation would be: If usage is greater than 60 or 70%, increase the size, otherwise all is good so you can leave it alone.

I take the same view with opcache shared memory size.

**Comment by samdark** [comment]
One may set it to 5 gigabytes (cause "more is better") so it totally worth checking if cache allocated is actually used. Since the script is to be executed on a particular server, cache will be warmed up if it runs real live code for some time.

Current code fits your criteria (but it won't suggest increasing cache size if it's not nearly full) so I'd leave it as is.
